package rules;
import com.sbnz.RestaurantForYou.events.FailedLogInEvent;
import com.sbnz.RestaurantForYou.model.*;


declare SuspiciousUserEvent
    @role(event)
    @expires(3m)
    user: User
    reason: String
end;

rule "More than 5 logging in unsuccessfully in 2 minute from one user"
    when
        $t1: FailedLogInEvent($id: user.getId(), $user: user)
        Number(intValue >= 5) from accumulate(
            $t2: FailedLogInEvent(
                this != $t1, 
                user.getId() == $id, 
                this meets[2m] $t1
            ),
            count($t2)
        )
        not (SuspiciousUserEvent(user.getId() == $id, reason == "More than 5 unsuccessful login attempts in 2 minutes from one user."))
    then
    	System.out.println("WARNING: More than 5 unsuccessful login attempts in 2 minutes from one user. ");
        insert(new SuspiciousUserEvent($user, "More than 5 unsuccessful login attempts in 2 minutes from one user."));
end;