package rules;
import com.sbnz.RestaurantForYou.model.Restaurant;
import com.sbnz.RestaurantForYou.model.RestaurantRrequirements;
import java.util.List;
import java.util.ArrayList;

global Restaurant bestRestaurant;

declare Processed
end

rule "The Best Restaurant" 
	agenda-group "recommendation"
	salience((100*$restaurant.calculateMatching($requirements)) / 10)
    when
		$requirements: RestaurantRrequirements();
		$restaurant: Restaurant($name: name, $value: score);
		not Processed()
    then	
    	bestRestaurant = $restaurant;
    	drools.getKnowledgeRuntime().setGlobal("bestRestaurant", $restaurant);
    	System.out.println("Restaurant: " + $name + " Matching: " + $value + " ===> ");  	
	    modify($requirements) { setProcessed(true) }
	    insert( new Processed() );
end;



